const fs=require('fs'),vm=require('vm'),assert=require('assert'),{webcrypto}=require('crypto');
const source=fs.readFileSync('src/web/WebAssets.h','utf8');const page=source.slice(source.indexOf('const char kSetup'),source.indexOf('const char kManage'));const script=page.match(/<script>([\s\S]*?)<\/script>/)[1];
assert(!/deviceName|adminPassphrase|browserName/.test(page));
assert.deepEqual([...page.matchAll(/<input id="([^"]+)"/g)].map(m=>m[1]),['ownerName','unlockSeconds','adminPin','pinConfirm']);
function browser(){const nodes={},store=new Map(),sent=[];for(const m of page.matchAll(/id="([^"]+)"/g))nodes[m[1]]={value:'',hidden:false,handlers:{},addEventListener(k,f){this.handlers[k]=f},setCustomValidity(){},reportValidity(){return true},reset(){}};
const location={search:'?session='+'a'.repeat(32),hostname:'smartlock-04225a0ff0a4.local',pathname:'/setup'};
const ctx={document:{getElementById(id){assert(nodes[id],id);return nodes[id]}},window:{location,crypto:webcrypto},location,crypto:webcrypto,URLSearchParams,TextEncoder,Uint8Array,localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)},fetch:async(path,opt)=>{if(path==='/api/status')return {ok:true,json:async()=>({canonicalHost:location.hostname})};sent.push(new URLSearchParams(opt.body));return {status:200,json:async()=>({ok:true,deviceId:'D000001',role:'Owner',apSsid:'SmartLock-F0A4'})}}};vm.runInNewContext(script,ctx);return {nodes,store,sent};}
(async()=>{for(const [pin,confirm] of [['123','123'],['12x4','12x4'],['5678','5679']]){const b=browser();Object.entries({ownerName:'Owner',unlockSeconds:'5',adminPin:pin,pinConfirm:confirm}).forEach(([k,v])=>b.nodes[k].value=v);await b.nodes.setupForm.handlers.submit({preventDefault(){}});assert.equal(b.sent.length,0);}
let credentials=[];for(let i=0;i<2;i++){const b=browser();Object.entries({ownerName:'Fresh Owner',unlockSeconds:'7',adminPin:'5678',pinConfirm:'5678'}).forEach(([k,v])=>b.nodes[k].value=v);await b.nodes.setupForm.handlers.submit({preventDefault(){}});const p=b.sent.find(p=>p.get('ownerName')==='Fresh Owner');assert(p);assert.equal(p.size,7);assert.equal(p.get('ownerName'),'Fresh Owner');assert.equal(p.get('pinConfirm'),'5678');assert(/^[a-f0-9]{64}$/.test(p.get('credential')));credentials.push(p.get('credential'));const saved=JSON.parse(b.store.get('smartlock.setup.v1'));assert.equal(saved.state,'active');assert.equal(saved.credential,p.get('credential'));assert(!b.store.get('smartlock.setup.v1').includes('5678'));assert.equal(b.nodes.adminPin.value,'');assert.equal(b.nodes.pinConfirm.value,'');}assert.notEqual(...credentials);const fresh=browser();Object.entries({ownerName:'Owner 1234',unlockSeconds:'5',adminPin:'1234',pinConfirm:'1234'}).forEach(([k,v])=>fresh.nodes[k].value=v);await fresh.nodes.setupForm.handlers.submit({preventDefault(){}});assert(fresh.sent.some(p=>p.get('adminPin')==='1234'));assert.equal(fresh.nodes.adminPin.value,'');assert.equal(fresh.nodes.pinConfirm.value,'');console.log('Fresh Setup browser checks PASS: four fields, 7-wire fields, 1234 accepted, PIN validation, independent opaque credential, secret clearing');})().catch(e=>{console.error(e);process.exitCode=1});
